/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: marvin <marvin@student.42.fr>              +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/11/23 10:40:45 by marvin            #+#    #+#             */
/*   Updated: 2024/11/23 10:40:45 by marvin           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "tests.h"

int	main(void)
{
	/* char c = 0;
	printf("//////////////////// Tests avec 'c' = 0 ////////////////////\n");
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%c|\n", c));
	fflush(stdout);
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10c|\n", c));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10c|\n", c));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010c|\n", c));
	fflush(stdout);
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10c|\n", c));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3c|\n", c));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3c|\n", c));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03c|\n", c));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3c|\n", c));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% c|\n", c));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+c|\n", c));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#c|\n", c));
	fflush(stdout);
	printf("\n\n\n");
	c = 'l';
	printf("//////////////////// Tests avec 'c' = '%c' ////////////////////\n", c);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%c|\n", c));
	fflush(stdout);
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10c|\n", c));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10c|\n", c));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010c|\n", c));
	fflush(stdout);
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10c|\n", c));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3c|\n", c));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3c|\n", c));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03c|\n", c));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3c|\n", c));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% c|\n", c));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+c|\n", c));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#c|\n", c));
	fflush(stdout);
	printf("\n\n\n"); */

	/* char *s = 0;
	printf("//////////////////// Tests avec 's' = %s ////////////////////\n", s);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%s|\n", s));
	fflush(stdout);
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10s|\n", s));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10s|\n", s));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010s|\n", s));
	fflush(stdout);
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10s|\n", s));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3s|\n", s));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3s|\n", s));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03s|\n", s));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3s|\n", s));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% s|\n", s));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+s|\n", s));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#s|\n", s));
	fflush(stdout);
	printf("\n\n\n");
	s = "";
	printf("//////////////////// Tests avec 's' = \"%s\" ////////////////////\n", s);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%s|\n", s));
	fflush(stdout);
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10s|\n", s));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10s|\n", s));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010s|\n", s));
	fflush(stdout);
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10s|\n", s));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3s|\n", s));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3s|\n", s));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03s|\n", s));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3s|\n", s));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% s|\n", s));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+s|\n", s));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#s|\n", s));
	fflush(stdout);
	printf("\n\n\n");
 */

	char *ptr = 0;
	printf("//////////////////// Tests avec 'p' = %p ////////////////////\n", ptr);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%p|\n", ptr));
	fflush(stdout);
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10p|\n", ptr));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10p|\n", ptr));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010p|\n", ptr));
	fflush(stdout);
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10p|\n", ptr));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3p|\n", ptr));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3p|\n", ptr));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03p|\n", ptr));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3p|\n", ptr));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% p|\n", ptr));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+p|\n", ptr));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#p|\n", ptr));
	fflush(stdout);
	printf("\n\n\n");
	void *ptr2 = (void *)0x0;
	printf("//////////////////// Tests avec 'p' = %p ////////////////////\n", ptr2);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%p|\n", ptr2));
	fflush(stdout);
	printf("/////test de champ 20/////\n");
	printf("original : %d\n", printf("original :   |%20p|\n", ptr2));
	fflush(stdout);
	printf("\n/////test de champ 20 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-20p|\n", ptr2));
	fflush(stdout);
	printf("\n/////test de champ 20 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%020p|\n", ptr2));
	fflush(stdout);
	printf("\n/////test 20 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.20p|\n", ptr2));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3p|\n", ptr2));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3p|\n", ptr2));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03p|\n", ptr2));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3p|\n", ptr2));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% p|\n", ptr2));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+p|\n", ptr2));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#p|\n", ptr2));
	fflush(stdout);
	printf("\n\n\n");

	/* int d = 0;
	printf("//////////////////// Tests avec 'd' = %d ////////////////////\n", d);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%d|\n", d));
	fflush(stdout);
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010d|\n", d));
	fflush(stdout);
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10d|\n", d));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03d|\n", d));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#d|\n", d));
	fflush(stdout);
	printf("\n\n\n");
	d = -123;
	printf("//////////////////// Tests avec 'd' = %d ////////////////////\n", d);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%d|\n", d));
	fflush(stdout);
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010d|\n", d));
	fflush(stdout);
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10d|\n", d));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03d|\n", d));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#d|\n", d));
	fflush(stdout);
	printf("\n\n\n");
	d = 1;
	printf("//////////////////// Tests avec 'd' = %d ////////////////////\n", d);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%d|\n", d));
	fflush(stdout);
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%+010d|\n", d));
	fflush(stdout);
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%+.10d|\n", d));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03d|\n", d));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+d|\n", d));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#d|\n", d));
	fflush(stdout);
	printf("\n\n\n"); */

	/* int i = 0;
	printf("//////////////////// Tests avec 'i' = %i ////////////////////\n", i);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%i|\n", i));
	fflush(stdout);
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010i|\n", i));
	fflush(stdout);
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10i|\n", i));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03i|\n", i));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#i|\n", i));
	fflush(stdout);
	printf("\n\n\n");
	i = -1;
	printf("//////////////////// Tests avec 'i' = %i ////////////////////\n", i);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%i|\n", i));
	fflush(stdout);
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010i|\n", i));
	fflush(stdout);
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10i|\n", i));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03i|\n", i));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#i|\n", i));
	fflush(stdout);
	printf("\n\n\n");
	i = 1;
	printf("//////////////////// Tests avec 'i' = %i ////////////////////\n", i);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%i|\n", i));
	fflush(stdout);
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010i|\n", i));
	fflush(stdout);
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10i|\n", i));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03i|\n", i));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+i|\n", i));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#i|\n", i));
	fflush(stdout);
	printf("\n\n\n"); */

	/* long u = 0;
	printf("//////////////////// Tests avec 'u' = %u ////////////////////\n", u);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%u|\n", u));
	fflush(stdout);
	printf("/////test de champ 15/////\n");
	printf("original : %d\n", printf("original :   |%15u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ 15 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-15u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ 15 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%015u|\n", u));
	fflush(stdout);
	printf("\n/////test 15 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.15u|\n", u));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03u|\n", u));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#u|\n", u));
	fflush(stdout);
	printf("\n\n\n");
	u = 1;
	printf("//////////////////// Tests avec 'u' = %u ////////////////////\n", u);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%u|\n", u));
	fflush(stdout);
	printf("/////test de champ 15/////\n");
	printf("original : %d\n", printf("original :   |%15u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ 15 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-15u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ 15 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%015u|\n", u));
	fflush(stdout);
	printf("\n/////test 15 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.15u|\n", u));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03u|\n", u));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#u|\n", u));
	fflush(stdout);
	printf("\n\n\n");
	u = -1;
	printf("//////////////////// Tests avec 'u' = %u ////////////////////\n", u);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%u|\n", u));
	fflush(stdout);
	printf("/////test de champ 15/////\n");
	printf("original : %d\n", printf("original :   |%15u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ 15 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-15u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ 15 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%015u|\n", u));
	fflush(stdout);
	printf("\n/////test 15 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.15u|\n", u));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03u|\n", u));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+u|\n", u));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#u|\n", u));
	fflush(stdout);
	printf("\n\n\n"); */

	/* int x = 0;
	printf("//////////////////// Tests avec 'x' pour x = %i ////////////////////\n", x);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%x|\n", x));
	fflush(stdout);
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010x|\n", x));
	fflush(stdout);
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10x|\n", x));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03x|\n", x));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#x|\n", x));
	fflush(stdout);
	printf("\n\n\n");
	x = -1;
	printf("//////////////////// Tests avec 'x' pour x = %i ////////////////////\n", x);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%x|\n", x));
	fflush(stdout);
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010x|\n", x));
	fflush(stdout);
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10x|\n", x));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03x|\n", x));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#x|\n", x));
	fflush(stdout);
	printf("\n\n\n");
	x = 1;
	printf("//////////////////// Tests avec 'x' pour x = %i ////////////////////\n", x);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%x|\n", x));
	fflush(stdout);
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010x|\n", x));
	fflush(stdout);
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10x|\n", x));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03x|\n", x));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+x|\n", x));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#x|\n", x));
	fflush(stdout);
	printf("\n\n\n"); */

	/* int x = 0;
	printf("//////////////////// Tests avec 'X' pour x = %i ////////////////////\n", x);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%X|\n", x));
	fflush(stdout);
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010X|\n", x));
	fflush(stdout);
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10X|\n", x));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03X|\n", x));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#X|\n", x));
	fflush(stdout);
	printf("\n\n\n");
	x = -1;
	printf("//////////////////// Tests avec 'X' pour x = %i ////////////////////\n", x);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%X|\n", x));
	fflush(stdout);
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010X|\n", x));
	fflush(stdout);
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10X|\n", x));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03X|\n", x));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#X|\n", x));
	fflush(stdout);
	printf("\n\n\n");
	x = 1;
	printf("//////////////////// Tests avec 'X' pour x = %i ////////////////////\n", x);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%X|\n", x));
	fflush(stdout);
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010X|\n", x));
	fflush(stdout);
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10X|\n", x));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03X|\n", x));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+X|\n", x));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#X|\n", x));
	fflush(stdout);
	printf("\n\n\n"); */

	/* printf("//////////////////// Tests avec '%%' ////////////////////\n");
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%%|\n"));
	fflush(stdout);
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10%|\n"));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10%|\n"));
	fflush(stdout);
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010%|\n"));
	fflush(stdout);
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10%|\n"));
	fflush(stdout);
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3%|\n"));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3%|\n"));
	fflush(stdout);
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03%|\n"));
	fflush(stdout);
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3%|\n"));
	fflush(stdout);
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% %|\n"));
	fflush(stdout);
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+%|\n"));
	fflush(stdout);
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#%|\n"));
	fflush(stdout);
	printf("\n\n\n"); */

}