/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   tests.c                                            :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: locagnio <locagnio@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/11/16 18:36:34 by locagnio          #+#    #+#             */
/*   Updated: 2024/11/24 19:52:55 by locagnio         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "tests.h"

void	tests_c(void)
{
	char c = 0;
	printf("//////////////////// Tests avec 'c' = 0 ////////////////////\n");
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%c|\n", c));
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%10c|\n", c));
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-10c|\n", c));
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%10c|\n", c));
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-3c|\n", c));
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%03c|\n", c));
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.3c|\n", c));
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |% c|\n", c));
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%+c|\n", c));
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%#c|\n", c));
	printf("\n\n\n");
	c = 'l';
	printf("//////////////////// Tests avec 'c' = '%c' ////////////////////\n", c);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%c|\n", c));
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%10c|\n", c));
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-10c|\n", c));
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%010c|\n", c));
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.10c|\n", c));
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%3c|\n", c));
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-3c|\n", c));
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%03c|\n", c));
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.3c|\n", c));
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |% c|\n", c));
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%+c|\n", c));
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#c|\n", c));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%#c|\n", c));
	printf("\n\n\n");
}

void	tests_s(void)
{
	char *s = 0;
	printf("//////////////////// Tests avec 's' = %s ////////////////////\n", s);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%s|\n", s));
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%10s|\n", s));
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-10s|\n", s));
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%010s|\n", s));
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.10s|\n", s));
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%3s|\n", s));
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-3s|\n", s));
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%03s|\n", s));
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.3s|\n", s));
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |% s|\n", s));
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%+s|\n", s));
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%#s|\n", s));
	printf("\n\n\n");
	s = "Yo boi";
	printf("//////////////////// Tests avec 's' = \"%s\" ////////////////////\n", s);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%s|\n", s));
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%10s|\n", s));
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-10s|\n", s));
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%010s|\n", s));
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.10s|\n", s));
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%3s|\n", s));
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-3s|\n", s));
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%03s|\n", s));
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.3s|\n", s));
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |% s|\n", s));
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%+s|\n", s));
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#s|\n", s));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%#s|\n", s));
	printf("\n\n\n");
}

void	tests_d(void)
{
	char *ptr = 0;
	printf("//////////////////// Tests avec 'p' = %p ////////////////////\n", ptr);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%p|\n", ptr));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%p|\n", ptr));
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10p|\n", ptr));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%10p|\n", ptr));
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10p|\n", ptr));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-10p|\n", ptr));
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010p|\n", ptr));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%010p|\n", ptr));
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10p|\n", ptr));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.10p|\n", ptr));
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3p|\n", ptr));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%3p|\n", ptr));
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3p|\n", ptr));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-3p|\n", ptr));
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03p|\n", ptr));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%03p|\n", ptr));
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3p|\n", ptr));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.3p|\n", ptr));
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% p|\n", ptr));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |% p|\n", ptr));
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+p|\n", ptr));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%+p|\n", ptr));
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#p|\n", ptr));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%#p|\n", ptr));
	printf("\n\n\n");
	void *ptr2 = (void *)0x343545;
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%p|\n", ptr2));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%p|\n", ptr2));
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10p|\n", ptr2));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%10p|\n", ptr2));
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10p|\n", ptr2));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-10p|\n", ptr2));
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010p|\n", ptr2));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%010p|\n", ptr2));
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10p|\n", ptr2));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.10p|\n", ptr2));
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3p|\n", ptr2));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%3p|\n", ptr2));
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3p|\n", ptr2));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-3p|\n", ptr2));
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03p|\n", ptr2));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%03p|\n", ptr2));
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3p|\n", ptr2));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.3p|\n", ptr2));
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% p|\n", ptr2));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |% p|\n", ptr2));
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+p|\n", ptr2));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%+p|\n", ptr2));
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#p|\n", ptr2));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%#p|\n", ptr2));
	printf("\n\n\n");
}

void	tests_i(void)
{
	int d = 0;
	printf("//////////////////// Tests avec 'd' = %d ////////////////////\n", d);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%d|\n", d));
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%10d|\n", d));
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-10d|\n", d));
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%010d|\n", d));
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.10d|\n", d));
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%3d|\n", d));
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-3d|\n", d));
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%03d|\n", d));
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.3d|\n", d));
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |% d|\n", d));
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%+d|\n", d));
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%#d|\n", d));
	printf("\n\n\n");
	d = -123;
	printf("//////////////////// Tests avec 'd' = %d ////////////////////\n", d);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%d|\n", d));
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%10d|\n", d));
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-10d|\n", d));
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%010d|\n", d));
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.10d|\n", d));
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%3d|\n", d));
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-3d|\n", d));
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%03d|\n", d));
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.3d|\n", d));
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |% d|\n", d));
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%+d|\n", d));
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%#d|\n", d));
	printf("\n\n\n");
	d = 1;
	printf("//////////////////// Tests avec 'd' = %d ////////////////////\n", d);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%d|\n", d));
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%10d|\n", d));
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-10d|\n", d));
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%010d|\n", d));
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.10d|\n", d));
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%3d|\n", d));
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-3d|\n", d));
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%03d|\n", d));
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.3d|\n", d));
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |% d|\n", d));
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%+d|\n", d));
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#d|\n", d));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%#d|\n", d));
	printf("\n\n\n");
}

void	tests_u(void)
{
	long u = 0;
	printf("//////////////////// Tests avec 'u' = %u ////////////////////\n", u);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%u|\n", u));
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%10u|\n", u));
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-10u|\n", u));
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%010u|\n", u));
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.10u|\n", u));
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%3u|\n", u));
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-3u|\n", u));
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%03u|\n", u));
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.3u|\n", u));
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |% u|\n", u));
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%+u|\n", u));
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%#u|\n", u));
	printf("\n\n\n");
	u = 1;
	printf("//////////////////// Tests avec 'u' = %u ////////////////////\n", u);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%u|\n", u));
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%10u|\n", u));
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-10u|\n", u));
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%010u|\n", u));
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.10u|\n", u));
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%3u|\n", u));
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-3u|\n", u));
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%03u|\n", u));
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.3u|\n", u));
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |% u|\n", u));
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%+u|\n", u));
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%#u|\n", u));
	printf("\n\n\n");
	u = -1;
	printf("//////////////////// Tests avec 'u' = %i ////////////////////\n", u);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%u|\n", u));
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%10u|\n", u));
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-10u|\n", u));
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%010u|\n", u));
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.10u|\n", u));
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%3u|\n", u));
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-3u|\n", u));
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%03u|\n", u));
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.3u|\n", u));
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |% u|\n", u));
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%+u|\n", u));
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#u|\n", u));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%#u|\n", u));
	printf("\n\n\n");
}

void	tests_x(int x)
{
	int x = 0;
	printf("//////////////////// Tests avec 'x' pour x = %i ////////////////////\n", x);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%x|\n", x));
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%10x|\n", x));
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-10x|\n", x));
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%010x|\n", x));
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.10x|\n", x));
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%3x|\n", x));
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-3x|\n", x));
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%03x|\n", x));
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.3x|\n", x));
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |% x|\n", x));
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%+x|\n", x));
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%#x|\n", x));
	printf("\n\n\n");
	x = -1;
	printf("//////////////////// Tests avec 'x' pour x = %i ////////////////////\n", x);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%x|\n", x));
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%10x|\n", x));
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-10x|\n", x));
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%010x|\n", x));
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.10x|\n", x));
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%3x|\n", x));
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-3x|\n", x));
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%03x|\n", x));
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.3x|\n", x));
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |% x|\n", x));
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%+x|\n", x));
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%#x|\n", x));
	printf("\n\n\n");
	x = 1;
	printf("//////////////////// Tests avec 'x' pour x = %i ////////////////////\n", x);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%x|\n", x));
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%10x|\n", x));
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-10x|\n", x));
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%010x|\n", x));
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.10x|\n", x));
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%3x|\n", x));
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-3x|\n", x));
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%03x|\n", x));
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.3x|\n", x));
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |% x|\n", x));
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%+x|\n", x));
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#x|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%#x|\n", x));
	printf("\n\n\n");
}

void	tests_x_maj(int x_maj)
{
	int x = 0;
	printf("//////////////////// Tests avec 'X' pour x = %i ////////////////////\n", x);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%X|\n", x));
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%10X|\n", x));
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-10X|\n", x));
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%010X|\n", x));
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.10X|\n", x));
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%3X|\n", x));
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-3X|\n", x));
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%03X|\n", x));
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.3X|\n", x));
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |% X|\n", x));
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%+X|\n", x));
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%#X|\n", x));
	printf("\n\n\n");
	x = -1;
	printf("//////////////////// Tests avec 'X' pour x = %i ////////////////////\n", x);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%X|\n", x));
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%10X|\n", x));
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-10X|\n", x));
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%010X|\n", x));
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.10X|\n", x));
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%3X|\n", x));
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-3X|\n", x));
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%03X|\n", x));
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.3X|\n", x));
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |% X|\n", x));
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%+X|\n", x));
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%#X|\n", x));
	printf("\n\n\n");
	x = 1;
	printf("//////////////////// Tests avec 'X' pour x = %i ////////////////////\n", x);
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%X|\n", x));
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%10X|\n", x));
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-10X|\n", x));
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%010X|\n", x));
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.10X|\n", x));
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%3X|\n", x));
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%-3X|\n", x));
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%03X|\n", x));
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%.3X|\n", x));
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |% X|\n", x));
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%+X|\n", x));
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#X|\n", x));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%#X|\n", x));
	printf("\n\n\n");
}

void	tests_percent(void)
{
	printf("//////////////////// Tests avec '%%' ////////////////////\n");
	printf("/////test sans flags/////\n");
	printf("original : %d\n", printf("original :   |%%|\n"));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%%|\n"));
	printf("/////test de champ 10/////\n");
	printf("original : %d\n", printf("original :   |%10%|\n"));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%%|\n"));
	printf("\n/////test de champ 10 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-10%|\n"));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%%|\n"));
	printf("\n/////test de champ 10 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%010%|\n"));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%%|\n"));
	printf("\n/////test 10 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.10%|\n"));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%%|\n"));
	printf("/////test de champ 3/////\n");
	printf("original : %d\n", printf("original :   |%3%|\n"));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%%|\n"));
	printf("\n/////test de champ 3 avec '-'/////\n");
	printf("original : %d\n", printf("original :   |%-3%|\n"));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%%|\n"));
	printf("\n/////test de champ 3 avec '0'/////\n");
	printf("original : %d\n", printf("original :   |%03%|\n"));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%%|\n"));
	printf("\n/////test 3 chiffres apres la virgule /////\n");
	printf("original : %d\n\n", printf("original :   |%.3%|\n"));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%%|\n"));
	printf("\n/////test de champ avec ' '/////\n");
	printf("original : %d\n", printf("original :   |% %|\n"));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%%|\n"));
	printf("\n/////test de champ avec '+'/////\n");
	printf("original : %d\n", printf("original :   |%+%|\n"));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%%|\n"));
	printf("\n/////test de champ avec '#'/////\n");
	printf("original : %d\n", printf("original :   |%#%|\n"));
	fflush(stdout);
	printf("copie    : %d\n", ft_printf("copie    :   |%%|\n"));
	printf("\n\n\n");
}
